---
- name: Ensure apt is using HTTPS
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present

- name: Install Docker CE
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Configure Docker daemon options
  ansible.builtin.template:
    src: "templates/docker_daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: "0755" # Optional file permissions
  notify: Restart Docker

- name: Ensure Docker service is enabled and running
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Login to private registry
  docker_login:
    registry: "{{ private_registry }}"
    username: "{{ registry_user }}"
    password: "{{ registry_password }}"

- name: Run 3 web application containers
  docker_container:
    name: "webapp-{{ item }}"
    image: "{{ private_registry }}/{{ webapp_image }}:{{ webapp_tag }}"
    state: started
    ports:
      - "800{{ item }}:80"
    pull: yes
    restart: yes
  loop: [1, 2, 3]
