apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: flask_app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask_app
  template:
    metadata:
      labels:
        app: flask_app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: nginx-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-volume
          emptyDir: {}